basic.forever(function on_forever() {
    basic.showString("Hi Madam")
    pins.servoWritePin(AnalogPin.P0, 116)
    basic.showString("My names is Chappie")
    basic.showIcon(IconNames.Heart)
    basic.showString("Can i ask you a question Madam ?")
    basic.showString("Which is the most used programming language in the world ?")
    basic.showString("A.Javascript")
    basic.showString("B.Python")
    basic.showString("C.MakeCode")
    basic.showString("Thank you for answering my question Madam ")
    basic.showString("BYE!")
})
